import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const scannerRoot = resolve(__dirname, '..');
const repoRoot = resolve(scannerRoot, '..', '..');

type HookEntry = {
  name: string;
  description?: string;
  payloadSchema?: Record<string, string>;
};

type RegistryFile = {
  version: number;
  description?: string;
  hooks: HookEntry[];
};

function loadRegistry(): RegistryFile {
  const p = join(repoRoot, 'FrikaModFramework', 'fmf_hooks.json');
  const raw = readFileSync(p, 'utf8');
  return JSON.parse(raw) as RegistryFile;
}

function generateHookDocs(registry: RegistryFile): string {
  const byDomain = new Map<string, HookEntry[]>();
  for (const h of registry.hooks) {
    const parts = h.name.split('.');
    const domain = parts.length >= 3 ? parts[1] : 'UNKNOWN';
    if (!byDomain.has(domain)) byDomain.set(domain, []);
    byDomain.get(domain)!.push(h);
  }

  const lines: string[] = [];
  lines.push('---');
  lines.push('id: fmf-hooks');
  lines.push('title: FMF Hook Reference');
  lines.push('sidebar_label: FMF Hook Reference');
  lines.push('description: Auto-generated from FrikaModFramework/fmf_hooks.json — run tools/fmf-hook-scanner.');
  lines.push('---');
  lines.push('');
  lines.push(':::info');
  lines.push('This page is generated by `tools/fmf-hook-scanner`. Do not edit by hand.');
  lines.push(':::');
  lines.push('');
  lines.push('# FMF Hook Reference');
  lines.push('');

  const domains = [...byDomain.keys()].sort();
  for (const d of domains) {
    lines.push(`## ${d}`);
    lines.push('');
    for (const h of byDomain.get(d)!) {
      lines.push(`### ${h.name}`);
      lines.push('');
      if (h.description) {
        lines.push(`**Description:** ${h.description}`);
        lines.push('');
      }
      if (h.payloadSchema && Object.keys(h.payloadSchema).length > 0) {
        lines.push('**Payload:**');
        lines.push('');
        for (const [k, t] of Object.entries(h.payloadSchema)) {
          lines.push(`- \`${k}\` (${t})`);
        }
        lines.push('');
      }
      lines.push('**Example (C#)**');
      lines.push('');
      lines.push('```csharp');
      lines.push(`FmfApi.On("${h.name}", payload => { });`);
      lines.push('```');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function writeGeneratedMdx(content: string): void {
  const out = join(repoRoot, 'docs', 'wiki', 'framework', 'fmf-hooks.mdx');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, content, 'utf8');
  console.log(`Wrote ${out}`);
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  const registry = loadRegistry();

  if (args.has('--docs')) {
    writeGeneratedMdx(generateHookDocs(registry));
  }

  if (args.has('--help') || args.size === 0) {
    console.log(`Usage: node dist/index.js [--docs] [--write-registry]

  --docs            Regenerate docs/wiki/framework/fmf-hooks.mdx from fmf_hooks.json
  --write-registry  (reserved) merge scan results into fmf_hooks.json

Repo root: ${repoRoot}`);
  }
}

main();
