<Project>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors Condition="'$(StrictCI)' == 'true'">true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS1701;CS1702;MSB3243;MSB3245</NoWarn>
  </PropertyGroup>
</Project>
