using Mono.Cecil;

// Module emission for GameApiGenerator (partial, behavior-preserving).
static partial class GameApiEmitter
{
    // Emits one module file and its registry entry.
    public static void EmitOne(TypeDefinition t, string genDir, List<string> registry, ref int generated, HashSet<string> keywords, HashSet<string> ambiguousTypeRefs)
    {
        try
        {
            var data = CollectAll(t);
            var line = WriteModule(data, genDir, keywords, ambiguousTypeRefs);
            registry.Add(line);
            generated++;
        }
        catch { }
    }

    // Builds source, writes the file and returns the registry line.
    private static string WriteModule(TypeData data, string genDir, HashSet<string> keywords, HashSet<string> ambiguousTypeRefs)
    {
        try
        {
            var canRef = IsRefable(data, ambiguousTypeRefs);
            var typeRef = GetTypeRef(data.Def);
            var sb = BuildSource(data, keywords, canRef, typeRef);
            var file = GetOutputFile(data, genDir, keywords);
            File.WriteAllText(file, sb.ToString());
            return BuildRegistryLine(data, keywords);
        }
        catch { return ""; }
    }

    // Decides whether the type can be referenced directly.
    private static bool IsRefable(TypeData data, HashSet<string> ambiguousTypeRefs)
    {
        try
        {
            return IsRefableCore(data.Names.IsGeneric, data.Kind, data.Def.Name, data.Def.FullName, ambiguousTypeRefs);
        }
        catch { return false; }
    }

    // Core referenceability rules.
    private static bool IsRefableCore(bool isGeneric, string kind, string name, string fullName, HashSet<string> ambiguous)
    {
        try
        {
            if (isGeneric) return false;
            if (!(kind is "Class" or "Component")) return false;
            if (name.StartsWith("_", StringComparison.Ordinal)) return false;
            return !ambiguous.Contains(fullName);
        }
        catch { return false; }
    }

    // Builds the global:: type reference.
    private static string GetTypeRef(TypeDefinition t)
    {
        try { return "global::" + t.FullName.Replace('/', '.'); }
        catch { return "global::System.Object"; }
    }

    // Resolves the output file path.
    private static string GetOutputFile(TypeData data, string genDir, HashSet<string> keywords)
    {
        try
        {
            var nsPath = data.Names.Ns.Replace('.', '/');
            var dir = Path.Combine(genDir, nsPath);
            Directory.CreateDirectory(dir);
            return Path.Combine(dir, Sanitize(data.Names.ShortName, keywords) + data.Names.Arity + ".g.cs");
        }
        catch { return Path.Combine(genDir, "Unknown.g.cs"); }
    }

    // Builds the full module source.
    private static System.Text.StringBuilder BuildSource(TypeData data, HashSet<string> keywords, bool canRef, string typeRef)
    {
        var sb = new System.Text.StringBuilder();
        try
        {
            AppendHeader(sb, data, keywords);
            AppendSingleton(sb, data, canRef, typeRef);
            AppendComponent(sb, data, canRef, typeRef);
            AppendMethods(sb, data, keywords, canRef, typeRef);
            AppendProps(sb, data, keywords);
            AppendFields(sb, data, keywords);
            AppendNested(sb, data, keywords);
            AppendEnum(sb, data, keywords);
            sb.AppendLine("}");
        }
        catch { }
        return sb;
    }

    // Appends file header and class opening.
    private static void AppendHeader(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            sb.AppendLine("// <auto-generated>GameApiGenerator: ilspycmd/Cecil dump of Assembly-CSharp. Do not edit by hand.</auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using HarmonyLib;");
            sb.AppendLine("using gregCore.Core.Abstractions;");
            sb.AppendLine("using gregCore.Core.Events;");
            sb.AppendLine();
            sb.AppendLine($"namespace gregCore.GameApi.{data.Names.Ns};");
            sb.AppendLine();
            sb.AppendLine($"/// <summary>Modder module for the game type <c>{data.Def.FullName}</c> ({data.Kind}).</summary>");
            sb.AppendLine($"public static class {Sanitize(data.Names.ShortName, keywords) + data.Names.Arity + "Module"}");
            sb.AppendLine("{");
            AppendHeaderConsts(sb, data);
        }
        catch { }
    }

    // Appends GameTypeName constants.
    private static void AppendHeaderConsts(System.Text.StringBuilder sb, TypeData data)
    {
        try
        {
            sb.AppendLine($"    public const string GameTypeName = \"{data.Def.FullName}\";");
            sb.AppendLine($"    public const string GameNamespace = \"{data.Def.Namespace}\";");
            sb.AppendLine($"    public const string Kind = \"{data.Kind}\";");
            sb.AppendLine($"    public const bool IsSingleton = {(data.SingletonMember != null ? "true" : "false")};");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends the TryGetSingleton helper.
    private static void AppendSingleton(System.Text.StringBuilder sb, TypeData data, bool canRef, string typeRef)
    {
        try
        {
            if (data.SingletonMember == null) return;
            if (!canRef) return;
            sb.AppendLine("    public static " + typeRef + "? TryGetSingleton()");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            var inst = {typeRef}.{data.SingletonMember};");
            sb.AppendLine("            if (inst == null || inst.Pointer == System.IntPtr.Zero) return null;");
            sb.AppendLine("            return inst;");
            sb.AppendLine("        }");
            sb.AppendLine("        catch { return null; }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends the TryFindFirst helper for components.
    private static void AppendComponent(System.Text.StringBuilder sb, TypeData data, bool canRef, string typeRef)
    {
        try
        {
            if (data.Kind != "Component") return;
            if (!canRef) return;
            sb.AppendLine("    public static " + typeRef + "? TryFindFirst() =>");
            sb.AppendLine($"        GregGameModuleHost.FindFirst<{typeRef}>();");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends Methods and Events constant groups.
    private static void AppendMethods(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords, bool canRef, string typeRef)
    {
        try
        {
            if (data.Methods.Count == 0) return;
            AppendMethodNames(sb, data, keywords);
            AppendEventNames(sb, data, keywords);
            AppendHookHelper(sb, data, canRef, typeRef);
        }
        catch { }
    }

    // Appends the Methods constants.
    private static void AppendMethodNames(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            sb.AppendLine("    public static class Methods");
            sb.AppendLine("    {");
            foreach (var (name, _) in data.Methods)
                sb.AppendLine($"        public const string {Sanitize(name, keywords)} = \"{name}\";");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends the Events constants.
    private static void AppendEventNames(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            sb.AppendLine("    public static class Events");
            sb.AppendLine("    {");
            foreach (var (name, _) in data.Methods)
                sb.AppendLine($"        public const string {Sanitize(name, keywords)} = \"greg.game.{data.Def.FullName}.{name}\";");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends the Hook helper.
    private static void AppendHookHelper(System.Text.StringBuilder sb, TypeData data, bool canRef, string typeRef)
    {
        try
        {
            if (!canRef) return;
            sb.AppendLine("    public static bool Hook(global::HarmonyLib.Harmony harmony, GregEventBus eventBus, IGregLogger logger, string methodName) =>");
            sb.AppendLine($"        GregGameModuleHost.HookMethod(harmony, typeof({typeRef}), methodName, eventBus, logger);");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends Properties constants.
    private static void AppendProps(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            if (data.Props.Count == 0) return;
            sb.AppendLine("    public static class Properties");
            sb.AppendLine("    {");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var p in data.Props)
            {
                var id = Sanitize(p, keywords);
                if (!seen.Add(id)) continue;
                sb.AppendLine($"        public const string {id} = \"{p}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends Fields constants.
    private static void AppendFields(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            if (data.Fields.Count == 0) return;
            sb.AppendLine("    public static class Fields");
            sb.AppendLine("    {");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var f in data.Fields)
            {
                var id = Sanitize(f, keywords);
                if (!seen.Add(id)) continue;
                sb.AppendLine($"        public const string {id} = \"{f}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Appends NestedTypes constants.
    private static void AppendNested(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            if (data.Nested.Count == 0) return;
            sb.AppendLine("    public static class NestedTypes");
            sb.AppendLine("    {");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < data.Nested.Count; i++)
            {
                var id = BuildNestedId(data.Nested[i], keywords, i, seen);
                sb.AppendLine($"        public const string {id} = \"{data.Nested[i]}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Builds a unique nested type identifier.
    private static string BuildNestedId(string full, HashSet<string> keywords, int index, HashSet<string> seen)
    {
        try
        {
            var id = Sanitize(full.Replace('/', '_'), keywords);
            if (string.IsNullOrEmpty(id)) id = $"Nested{index}";
            var baseId = id;
            var n = 1;
            while (!seen.Add(id)) id = $"{baseId}_{n++}";
            return id;
        }
        catch { return $"Nested{index}"; }
    }

    // Appends enum Values constants.
    private static void AppendEnum(System.Text.StringBuilder sb, TypeData data, HashSet<string> keywords)
    {
        try
        {
            if (data.EnumValues.Count == 0) return;
            sb.AppendLine("    public static class Values");
            sb.AppendLine("    {");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var (name, value) in data.EnumValues)
            {
                var id = Sanitize(name, keywords);
                if (!seen.Add(id)) continue;
                sb.AppendLine($"        public const string {id} = \"{name}\"; // = {value}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        catch { }
    }

    // Builds the registry descriptor line.
    private static string BuildRegistryLine(TypeData data, HashSet<string> keywords)
    {
        try
        {
            return $"        new GameApiModuleDescriptor {{ GameTypeName = \"{data.Def.FullName}\", ModuleTypeName = \"gregCore.GameApi.{data.Names.Ns}.{Sanitize(data.Names.ShortName, keywords) + data.Names.Arity + "Module"}\", Kind = \"{data.Kind}\", IsSingleton = {(data.SingletonMember != null ? "true" : "false")}, IsGeneric = {(data.Names.IsGeneric ? "true" : "false")}, MethodCount = {data.Methods.Count} }},";
        }
        catch { return ""; }
    }

    // NOTE: header/module naming uses caller-provided keywords for short names;
    // the record above keeps behavior identical to Program.cs (sanitized shortName+arity).
    public static string ModuleName(TypeNames names, HashSet<string> keywords)
    {
        try { return Sanitize(names.ShortName, keywords) + names.Arity + "Module"; }
        catch { return "UnknownModule"; }
    }
}
