using Mono.Cecil;

// Generates one gregCore GameApi module per top-level game type, alphabetical.
// Usage: gameapi-gen <Assembly-CSharp.dll> <refs-dir> <out-dir>
var asmPath = args[0];
var refsDir = args[1];
var outDir = args[2];
var genDir = Path.Combine(outDir, "Generated");

var resolver = new DefaultAssemblyResolver();
resolver.AddSearchDirectory(Path.GetDirectoryName(asmPath)!);
if (Directory.Exists(refsDir)) resolver.AddSearchDirectory(refsDir);
var asm = AssemblyDefinition.ReadAssembly(asmPath, new ReaderParameters { AssemblyResolver = resolver });

var keywords = new HashSet<string>(StringComparer.Ordinal)
{
    "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
    "continue","decimal","default","delegate","do","double","else","enum","event","explicit",
    "extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int",
    "interface","internal","is","lock","long","namespace","new","null","object","operator","out",
    "override","params","private","protected","public","readonly","ref","return","sbyte","sealed",
    "short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
    "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
};

static string Sanitize(string name, HashSet<string> kw)
{
    try { return GameApiEmitter.Sanitize(name, kw); }
    catch { return "_"; }
}

bool IsComponent(TypeDefinition t)
{
    try { return GameApiEmitter.IsComponent(t); }
    catch { return false; }
}

var types = asm.MainModule.Types
    .Where(t => t.Name != "<Module>")
    .OrderBy(t => t.FullName, StringComparer.OrdinalIgnoreCase)
    .ToList();

var ambiguousTypeRefs = new HashSet<string>(StringComparer.Ordinal)
{
    "Unity.Entities.CodeGeneratedRegistry.AssemblyTypeRegistry",
    "Il2Cpp._PrivateImplementationDetails_",
    "Il2Cpp.UnitySourceGeneratedAssemblyMonoScriptTypes_v1",
};

var sourceSha = "";
var registry = new List<string>();
var generated = 0;

foreach (var t in types)
{
    try { GameApiEmitter.EmitOne(t, genDir, registry, ref generated, keywords, ambiguousTypeRefs); }
    catch { /* ignored: defensive best-effort (CONVENTIONS.md) */ }
}

using (var stream = File.OpenRead(asmPath))
{
    var hash = System.Security.Cryptography.SHA256.HashData(stream);
    sourceSha = Convert.ToHexString(hash).ToLowerInvariant();
}

var regPath = Path.Combine(genDir, "GregGameApiRegistry.g.cs");
var reg = new System.Text.StringBuilder();
reg.AppendLine("// <auto-generated>GameApiGenerator registry. Do not edit by hand.</auto-generated>");
reg.AppendLine("using System;");
reg.AppendLine("using System.Collections.Generic;");
reg.AppendLine();
reg.AppendLine("namespace gregCore.GameApi;");
reg.AppendLine();
reg.AppendLine("public sealed record GameApiModuleDescriptor");
reg.AppendLine("{");
reg.AppendLine("    public string GameTypeName { get; init; } = string.Empty;");
reg.AppendLine("    public string ModuleTypeName { get; init; } = string.Empty;");
reg.AppendLine("    public string Kind { get; init; } = string.Empty;");
reg.AppendLine("    public bool IsSingleton { get; init; }");
reg.AppendLine("    public bool IsGeneric { get; init; }");
reg.AppendLine("    public int MethodCount { get; init; }");
reg.AppendLine("}");
reg.AppendLine();
reg.AppendLine("public static class GregGameApiRegistry");
reg.AppendLine("{");
reg.AppendLine("    public const string GeneratorVersion = \"1.1.0\";");
reg.AppendLine($"    public const string SourceAssembly = \"Assembly-CSharp.dll\";");
reg.AppendLine($"    public const string SourceSha256 = \"{sourceSha}\";");
reg.AppendLine($"    public const string GeneratedUtc = \"{DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\";");
reg.AppendLine($"    public const int ModuleCount = {registry.Count};");
reg.AppendLine("    public static readonly IReadOnlyList<GameApiModuleDescriptor> Modules = new List<GameApiModuleDescriptor>");
reg.AppendLine("    {");
foreach (var line in registry) reg.AppendLine(line);
reg.AppendLine("    }.AsReadOnly();");
reg.AppendLine();
reg.AppendLine("    public static GameApiModuleDescriptor? TryGetModule(string gameTypeName)");
reg.AppendLine("    {");
reg.AppendLine("        if (string.IsNullOrWhiteSpace(gameTypeName)) return null;");
reg.AppendLine("        foreach (var m in Modules)");
reg.AppendLine("            if (string.Equals(m.GameTypeName, gameTypeName, StringComparison.Ordinal)) return m;");
reg.AppendLine("        return null;");
reg.AppendLine("    }");
reg.AppendLine("}");
File.WriteAllText(regPath, reg.ToString());
