#requires -Version 5.1
<#
.SYNOPSIS
  Regenerates gregWiki/docs/reference/greg-hooks-catalog.md from GregNativeEventHooks.cs and EventIds in EventDispatcher.cs
#>
param(
    [switch]$SkipChangelogNote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $PSCommandPath }
$repoRoot = Resolve-Path (Join-Path $scriptRoot '..')
$nativeHooksPath = Join-Path $repoRoot 'framework/Sdk/GregNativeEventHooks.cs'
$eventDispatcherPath = Join-Path $repoRoot 'framework/ModLoader/EventDispatcher.cs'
$outPath = Join-Path $repoRoot '../gregWiki/docs/reference/greg-hooks-catalog.md'

if (-not (Test-Path -LiteralPath $nativeHooksPath)) {
    throw "Not found: $nativeHooksPath"
}
if (-not (Test-Path -LiteralPath $eventDispatcherPath)) {
    throw "Not found: $eventDispatcherPath"
}
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $outDir)) {
    throw "Wiki docs folder not found: $outDir. Clone gregWiki next to gregCore or set a custom output path."
}

$hookSource = Get-Content -LiteralPath $nativeHooksPath -Raw
$dispatcherSource = Get-Content -LiteralPath $eventDispatcherPath -Raw

# public const string Name = "greg....";
$constRegex = 'public const string (?<field>\w+)\s*=\s*"(?<hook>[^"]+)";'
$hookRows = [System.Collections.Generic.List[object]]::new()
foreach ($m in [regex]::Matches($hookSource, $constRegex)) {
    $hookRows.Add([ordered]@{
            Field = $m.Groups['field'].Value
            Hook  = $m.Groups['hook'].Value
        })
}

# public static readonly string X = GregHookName.Create(...) — capture assigned expression for docs
$readonlyRegex = 'public static readonly string (?<field>\w+)\s*=\s*(?<expr>[^;]+);'
foreach ($m in [regex]::Matches($hookSource, $readonlyRegex)) {
    $hookRows.Add([ordered]@{
            Field = $m.Groups['field'].Value
            Hook  = $m.Groups['expr'].Value.Trim()
        })
}

# [EventIds.Something] = FieldName,
$mapRegex = '\[\s*EventIds\.(?<ev>\w+)\s*\]\s*=\s*(?<field>\w+)\s*,'
$idToField = @{}
foreach ($m in [regex]::Matches($hookSource, $mapRegex)) {
    $idToField[$m.Groups['ev'].Value] = $m.Groups['field'].Value
}

# EventIds block in EventDispatcher.cs
$evSection = [regex]::Match($dispatcherSource, 'public static class EventIds\s*\{(?<body>[\s\S]*?)\n\}')
if (-not $evSection.Success) {
    throw 'Could not find EventIds class in EventDispatcher.cs'
}
$evRegex = 'public const uint (?<name>\w+)\s*=\s*(?<num>\d+)\s*;'
$eventNums = @{}
foreach ($m in [regex]::Matches($evSection.Groups['body'].Value, $evRegex)) {
    $eventNums[$m.Groups['name'].Value] = [uint32]$m.Groups['num'].Value
}

$generatedUtc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC')
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('id: greg-hooks-catalog')
[void]$sb.AppendLine('title: greg hooks catalog')
[void]$sb.AppendLine('slug: /reference/greg-hooks-catalog')
[void]$sb.AppendLine('description: Auto-generated catalog of native pipeline hook strings from GregNativeEventHooks.')
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('<!-- AUTO-GENERATED by tools/Generate-GregHookCatalog.ps1 - DO NOT EDIT BY HAND -->')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('# greg hooks catalog')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('This page is **generated** from `gregCore/framework/Sdk/GregNativeEventHooks.cs` and `EventIds` in `EventDispatcher.cs`.')
if (-not $SkipChangelogNote) {
    [void]$sb.AppendLine('Regenerate after hook changes: `./tools/Generate-GregHookCatalog.ps1`')
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine("**Generated:** $generatedUtc")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Hook string constants')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| C# field | Hook string / expression |')
[void]$sb.AppendLine('|----------|----------------------------|')

$seen = @{}
foreach ($row in ($hookRows | Sort-Object { $_.Hook })) {
    if ($seen.ContainsKey($row.Field)) { continue }
    $seen[$row.Field] = $true
    [void]$sb.AppendLine('| ``' + $row.Field + '`` | ``' + $row.Hook + '`` |')
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Event id to hook mapping')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Event id (uint) | EventIds name | GregNativeEventHooks field | Hook string |')
[void]$sb.AppendLine('|-----------------|---------------|----------------------------|-------------|')

function Resolve-HookStr {
    param($field, $hookRows)
    $row = $hookRows | Where-Object { $_.Field -eq $field } | Select-Object -First 1
    if ($row) { return $row.Hook }
    return '*(see source)*'
}

foreach ($evName in ($idToField.Keys | Sort-Object)) {
    $field = $idToField[$evName]
    if (-not $eventNums.ContainsKey($evName)) { continue }
    $num = $eventNums[$evName]
    $hookStr = Resolve-HookStr -field $field -hookRows $hookRows
    [void]$sb.AppendLine("| $num | ``$evName`` | ``$field`` | ``$hookStr`` |")
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Fallback')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Unknown event ids resolve to ``greg.SYSTEM.UnmappedNativeEvent`` via ``GregNativeEventHooks.Resolve``.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## See also')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('- [greg hook naming](./greg-hook-naming.md)')
[void]$sb.AppendLine('- [EventIds source](https://github.com/mleem97/gregFramework/blob/main/gregCore/framework/ModLoader/EventDispatcher.cs)')
[void]$sb.AppendLine('- [GregNativeEventHooks source](https://github.com/mleem97/gregFramework/blob/main/gregCore/framework/Sdk/GregNativeEventHooks.cs)')
[void]$sb.AppendLine('- [Greg hooks & event runtime](/wiki/framework/greg-hooks-and-events)')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $outPath"
