#!/usr/bin/env python3
"""
generate_api_docs.py
Generates docs/FrameworkAPI.md from game_hooks.json and framework/greg_hooks.json.

Usage:
  python3 scripts/generate_api_docs.py \
      --game-hooks game_hooks.json \
      --greg-hooks framework/greg_hooks.json \
      --output docs/FrameworkAPI.md \
      --version 1.2.3
"""
import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import date


def load_json(path: str) -> "dict | list | None":
    if not os.path.isfile(path):
        print(f"[warn] File not found: {path}", file=sys.stderr)
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def format_params(params: list) -> str:
    if not params:
        return "()"
    parts = [f"{p.get('Type', '?')} {p.get('Name', '?')}" for p in params]
    return "(" + ", ".join(parts) + ")"


def render_game_hooks(data: list) -> str:
    if not data:
        return "_No game hooks defined._\n"
    groups: defaultdict[str, list] = defaultdict(list)
    for entry in data:
        groups[entry.get("Group", "Uncategorized")].append(entry)

    lines = []
    for group_name in sorted(groups):
        lines.append(f"### {group_name}\n")
        lines.append("| Class | Method | Return | Parameters |")
        lines.append("|-------|--------|--------|------------|")
        for h in sorted(groups[group_name], key=lambda x: (x.get("ClassName", ""), x.get("MethodName", ""))):
            cls = h.get("ClassName", "?")
            ns = h.get("Namespace", "")
            full_cls = f"`{ns}.{cls}`" if ns else f"`{cls}`"
            method = h.get("MethodName", "?")
            ret = h.get("ReturnType", "?")
            params = format_params(h.get("Parameters", []))
            lines.append(f"| {full_cls} | `{method}` | `{ret}` | `{params}` |")
        lines.append("")
    return "\n".join(lines)


def render_greg_hooks(data: dict) -> str:
    if not data:
        return "_No greg hooks defined._\n"
    hooks = data.get("hooks", [])
    if not hooks:
        return "_Hook registry is empty._\n"

    # Group by name prefix (e.g. greg.SYSTEM, greg.AUDIO …)
    groups: defaultdict[str, list] = defaultdict(list)
    for h in hooks:
        name: str = h.get("name", "")
        parts = name.split(".")
        group = parts[1] if len(parts) >= 2 else "OTHER"
        groups[group].append(h)

    lines = []
    for group_name in sorted(groups):
        lines.append(f"### {group_name}\n")
        lines.append("| Hook Name | Patch Target | Strategy | Description |")
        lines.append("|-----------|-------------|----------|-------------|")
        for h in sorted(groups[group_name], key=lambda x: x.get("name", "")):
            hook_name = h.get("name", "")
            target = h.get("patchTarget", "")
            strategy = h.get("strategy", "")
            desc = h.get("description", "")
            lines.append(f"| `{hook_name}` | `{target}` | `{strategy}` | {desc} |")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate FrameworkAPI.md from hook JSON files.")
    parser.add_argument("--game-hooks", required=True, help="Path to game_hooks.json")
    parser.add_argument("--greg-hooks", required=True, help="Path to framework/greg_hooks.json")
    parser.add_argument("--output", required=True, help="Output markdown file path")
    parser.add_argument("--version", default="?", help="Current framework version")
    args = parser.parse_args()

    game_hooks = load_json(args.game_hooks)
    greg_hooks = load_json(args.greg_hooks)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    today = date.today().isoformat()
    game_section = render_game_hooks(game_hooks if isinstance(game_hooks, list) else [])
    greg_section = render_greg_hooks(greg_hooks if isinstance(greg_hooks, dict) else {})

    doc = f"""# gregCore FrameworkAPI Reference

> **Version:** {args.version} | **Generated:** {today}
>
> Auto-generated from `game_hooks.json` and `framework/greg_hooks.json`.
> Do not edit manually — re-run the generator or push changes to the source JSON files.

---

## Table of Contents

1. [Game Hooks (game_hooks.json)](#1-game-hooks)
2. [Greg Hooks (greg_hooks.json)](#2-greg-hooks)

---

## 1. Game Hooks

These hooks describe patchable methods extracted from the game's IL2CPP assembly.
They serve as the raw targets for Harmony Prefix/Postfix patches.

{game_section}

---

## 2. Greg Hooks

These are the canonical greg-domain hooks registered in the framework hook bus.
Use them in your mod's event subscriptions.

{greg_section}

---

*Generated by `scripts/generate_api_docs.py` — see [README.md](../README.md) for details.*
"""

    with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(doc)

    print(f"[ok] Wrote {args.output}")


if __name__ == "__main__":
    main()
